services:
  {{project_name}}:
    build:
      context: .
      dockerfile: Dockerfile
      target: runtime
      args:
        NODE_VERSION: ${NODE_VERSION:-22}
        PNPM_VERSION: ${PNPM_VERSION:-10.11.0}
        APP_PORT: ${APP_PORT:-4321}
      x-bake:
        output:
          - type=docker
        cache-from:
          - type=inline
        platforms:
          - linux/amd64
    image: {{project_name}}:${IMAGE_TAG:-latest}
    container_name: ${CONTAINER_NAME:-{{project_name}}}
    ports:
      - "${HOST_PORT:-4321}:${APP_PORT:-4321}"
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - HOST=0.0.0.0
      - PORT=${APP_PORT:-4321}
      - ASTRO_TELEMETRY_DISABLED=1
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:4321',r=>process.exit(r.statusCode===200?0:1)).on('error',()=>process.exit(1))"]
      interval: 30s
      timeout: 10s
      start_period: 10s
      retries: 3
    # Basic resource limits
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
    # Logging configuration
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"